//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class datafilmEntities : DbContext
    {
        public datafilmEntities()
            : base("name=datafilmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aspnet_Applications> aspnet_Applications { get; set; }
        public virtual DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public virtual DbSet<aspnet_Paths> aspnet_Paths { get; set; }
        public virtual DbSet<aspnet_PersonalizationAllUsers> aspnet_PersonalizationAllUsers { get; set; }
        public virtual DbSet<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }
        public virtual DbSet<aspnet_Profile> aspnet_Profile { get; set; }
        public virtual DbSet<aspnet_Roles> aspnet_Roles { get; set; }
        public virtual DbSet<aspnet_SchemaVersions> aspnet_SchemaVersions { get; set; }
        public virtual DbSet<aspnet_Users> aspnet_Users { get; set; }
        public virtual DbSet<aspnet_WebEvent_Events> aspnet_WebEvent_Events { get; set; }
        public virtual DbSet<CoDinhTyLePhuSon> CoDinhTyLePhuSons { get; set; }
        public virtual DbSet<CoDinhTyLeTaoMach> CoDinhTyLeTaoMaches { get; set; }
        public virtual DbSet<LoaiPhim> LoaiPhims { get; set; }
        public virtual DbSet<PhimFpc> PhimFpcs { get; set; }
        public virtual DbSet<PhimPcb> PhimPcbs { get; set; }
        public virtual DbSet<PhimTest> PhimTests { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual int Delete_Fpc(Nullable<int> idfpc)
        {
            var idfpcParameter = idfpc.HasValue ?
                new ObjectParameter("idfpc", idfpc) :
                new ObjectParameter("idfpc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Fpc", idfpcParameter);
        }
    
        public virtual int Delete_Phimpcb(Nullable<int> idpcb)
        {
            var idpcbParameter = idpcb.HasValue ?
                new ObjectParameter("idpcb", idpcb) :
                new ObjectParameter("idpcb", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Phimpcb", idpcbParameter);
        }
    
        public virtual int Delete_TaoMach(Nullable<int> idtaomach)
        {
            var idtaomachParameter = idtaomach.HasValue ?
                new ObjectParameter("idtaomach", idtaomach) :
                new ObjectParameter("idtaomach", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_TaoMach", idtaomachParameter);
        }
    
        public virtual int Delete_Test(Nullable<int> idtest)
        {
            var idtestParameter = idtest.HasValue ?
                new ObjectParameter("idtest", idtest) :
                new ObjectParameter("idtest", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Test", idtestParameter);
        }
    
        public virtual int DeletePhuSon(Nullable<int> idphuson)
        {
            var idphusonParameter = idphuson.HasValue ?
                new ObjectParameter("idphuson", idphuson) :
                new ObjectParameter("idphuson", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeletePhuSon", idphusonParameter);
        }
    
        public virtual int Insert_Fpc(string ca, Nullable<System.DateTime> ngay, string gio, string bophan, string tensanpham, string phanloai, string loaiphim, Nullable<int> sobo, string tylex, string tyley, string nguoiyeucau, string noidungyeucau, string xacnhancam, string mayin, string hientrang, string giohoanthanh, string ngayxuatxuong, string ngaybaophe, string noidungbaophe)
        {
            var caParameter = ca != null ?
                new ObjectParameter("ca", ca) :
                new ObjectParameter("ca", typeof(string));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            var gioParameter = gio != null ?
                new ObjectParameter("gio", gio) :
                new ObjectParameter("gio", typeof(string));
    
            var bophanParameter = bophan != null ?
                new ObjectParameter("bophan", bophan) :
                new ObjectParameter("bophan", typeof(string));
    
            var tensanphamParameter = tensanpham != null ?
                new ObjectParameter("tensanpham", tensanpham) :
                new ObjectParameter("tensanpham", typeof(string));
    
            var phanloaiParameter = phanloai != null ?
                new ObjectParameter("phanloai", phanloai) :
                new ObjectParameter("phanloai", typeof(string));
    
            var loaiphimParameter = loaiphim != null ?
                new ObjectParameter("loaiphim", loaiphim) :
                new ObjectParameter("loaiphim", typeof(string));
    
            var soboParameter = sobo.HasValue ?
                new ObjectParameter("sobo", sobo) :
                new ObjectParameter("sobo", typeof(int));
    
            var tylexParameter = tylex != null ?
                new ObjectParameter("tylex", tylex) :
                new ObjectParameter("tylex", typeof(string));
    
            var tyleyParameter = tyley != null ?
                new ObjectParameter("tyley", tyley) :
                new ObjectParameter("tyley", typeof(string));
    
            var nguoiyeucauParameter = nguoiyeucau != null ?
                new ObjectParameter("nguoiyeucau", nguoiyeucau) :
                new ObjectParameter("nguoiyeucau", typeof(string));
    
            var noidungyeucauParameter = noidungyeucau != null ?
                new ObjectParameter("noidungyeucau", noidungyeucau) :
                new ObjectParameter("noidungyeucau", typeof(string));
    
            var xacnhancamParameter = xacnhancam != null ?
                new ObjectParameter("xacnhancam", xacnhancam) :
                new ObjectParameter("xacnhancam", typeof(string));
    
            var mayinParameter = mayin != null ?
                new ObjectParameter("mayin", mayin) :
                new ObjectParameter("mayin", typeof(string));
    
            var hientrangParameter = hientrang != null ?
                new ObjectParameter("hientrang", hientrang) :
                new ObjectParameter("hientrang", typeof(string));
    
            var giohoanthanhParameter = giohoanthanh != null ?
                new ObjectParameter("giohoanthanh", giohoanthanh) :
                new ObjectParameter("giohoanthanh", typeof(string));
    
            var ngayxuatxuongParameter = ngayxuatxuong != null ?
                new ObjectParameter("ngayxuatxuong", ngayxuatxuong) :
                new ObjectParameter("ngayxuatxuong", typeof(string));
    
            var ngaybaopheParameter = ngaybaophe != null ?
                new ObjectParameter("ngaybaophe", ngaybaophe) :
                new ObjectParameter("ngaybaophe", typeof(string));
    
            var noidungbaopheParameter = noidungbaophe != null ?
                new ObjectParameter("noidungbaophe", noidungbaophe) :
                new ObjectParameter("noidungbaophe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Fpc", caParameter, ngayParameter, gioParameter, bophanParameter, tensanphamParameter, phanloaiParameter, loaiphimParameter, soboParameter, tylexParameter, tyleyParameter, nguoiyeucauParameter, noidungyeucauParameter, xacnhancamParameter, mayinParameter, hientrangParameter, giohoanthanhParameter, ngayxuatxuongParameter, ngaybaopheParameter, noidungbaopheParameter);
        }
    
        public virtual int Insert_LoaiPhim(string loaiphim)
        {
            var loaiphimParameter = loaiphim != null ?
                new ObjectParameter("loaiphim", loaiphim) :
                new ObjectParameter("loaiphim", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_LoaiPhim", loaiphimParameter);
        }
    
        public virtual int Insert_PhimPcb(string ca, Nullable<System.DateTime> ngay, string gio, string bophan, string masanpham, string phanloai, string loaiphim, string maydung, Nullable<int> sobo, string tylex, string tyley, string nguoiyeucau, string noidungyeucau, string xacnhanpe, string xacnhancam, string mayin, string hientrang, string giohoanthanh, string ngayxuatxuong, string ngaybaophe, string noidungbaophe)
        {
            var caParameter = ca != null ?
                new ObjectParameter("ca", ca) :
                new ObjectParameter("ca", typeof(string));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            var gioParameter = gio != null ?
                new ObjectParameter("gio", gio) :
                new ObjectParameter("gio", typeof(string));
    
            var bophanParameter = bophan != null ?
                new ObjectParameter("bophan", bophan) :
                new ObjectParameter("bophan", typeof(string));
    
            var masanphamParameter = masanpham != null ?
                new ObjectParameter("masanpham", masanpham) :
                new ObjectParameter("masanpham", typeof(string));
    
            var phanloaiParameter = phanloai != null ?
                new ObjectParameter("phanloai", phanloai) :
                new ObjectParameter("phanloai", typeof(string));
    
            var loaiphimParameter = loaiphim != null ?
                new ObjectParameter("loaiphim", loaiphim) :
                new ObjectParameter("loaiphim", typeof(string));
    
            var maydungParameter = maydung != null ?
                new ObjectParameter("maydung", maydung) :
                new ObjectParameter("maydung", typeof(string));
    
            var soboParameter = sobo.HasValue ?
                new ObjectParameter("sobo", sobo) :
                new ObjectParameter("sobo", typeof(int));
    
            var tylexParameter = tylex != null ?
                new ObjectParameter("tylex", tylex) :
                new ObjectParameter("tylex", typeof(string));
    
            var tyleyParameter = tyley != null ?
                new ObjectParameter("tyley", tyley) :
                new ObjectParameter("tyley", typeof(string));
    
            var nguoiyeucauParameter = nguoiyeucau != null ?
                new ObjectParameter("nguoiyeucau", nguoiyeucau) :
                new ObjectParameter("nguoiyeucau", typeof(string));
    
            var noidungyeucauParameter = noidungyeucau != null ?
                new ObjectParameter("noidungyeucau", noidungyeucau) :
                new ObjectParameter("noidungyeucau", typeof(string));
    
            var xacnhanpeParameter = xacnhanpe != null ?
                new ObjectParameter("xacnhanpe", xacnhanpe) :
                new ObjectParameter("xacnhanpe", typeof(string));
    
            var xacnhancamParameter = xacnhancam != null ?
                new ObjectParameter("xacnhancam", xacnhancam) :
                new ObjectParameter("xacnhancam", typeof(string));
    
            var mayinParameter = mayin != null ?
                new ObjectParameter("mayin", mayin) :
                new ObjectParameter("mayin", typeof(string));
    
            var hientrangParameter = hientrang != null ?
                new ObjectParameter("hientrang", hientrang) :
                new ObjectParameter("hientrang", typeof(string));
    
            var giohoanthanhParameter = giohoanthanh != null ?
                new ObjectParameter("giohoanthanh", giohoanthanh) :
                new ObjectParameter("giohoanthanh", typeof(string));
    
            var ngayxuatxuongParameter = ngayxuatxuong != null ?
                new ObjectParameter("ngayxuatxuong", ngayxuatxuong) :
                new ObjectParameter("ngayxuatxuong", typeof(string));
    
            var ngaybaopheParameter = ngaybaophe != null ?
                new ObjectParameter("ngaybaophe", ngaybaophe) :
                new ObjectParameter("ngaybaophe", typeof(string));
    
            var noidungbaopheParameter = noidungbaophe != null ?
                new ObjectParameter("noidungbaophe", noidungbaophe) :
                new ObjectParameter("noidungbaophe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_PhimPcb", caParameter, ngayParameter, gioParameter, bophanParameter, masanphamParameter, phanloaiParameter, loaiphimParameter, maydungParameter, soboParameter, tylexParameter, tyleyParameter, nguoiyeucauParameter, noidungyeucauParameter, xacnhanpeParameter, xacnhancamParameter, mayinParameter, hientrangParameter, giohoanthanhParameter, ngayxuatxuongParameter, ngaybaopheParameter, noidungbaopheParameter);
        }
    
        public virtual int Insert_PhuSon(string tensanpham, string loaiphim, string tylexmin, string tylexmax, string tyleymin, string tyleymax)
        {
            var tensanphamParameter = tensanpham != null ?
                new ObjectParameter("tensanpham", tensanpham) :
                new ObjectParameter("tensanpham", typeof(string));
    
            var loaiphimParameter = loaiphim != null ?
                new ObjectParameter("loaiphim", loaiphim) :
                new ObjectParameter("loaiphim", typeof(string));
    
            var tylexminParameter = tylexmin != null ?
                new ObjectParameter("tylexmin", tylexmin) :
                new ObjectParameter("tylexmin", typeof(string));
    
            var tylexmaxParameter = tylexmax != null ?
                new ObjectParameter("tylexmax", tylexmax) :
                new ObjectParameter("tylexmax", typeof(string));
    
            var tyleyminParameter = tyleymin != null ?
                new ObjectParameter("tyleymin", tyleymin) :
                new ObjectParameter("tyleymin", typeof(string));
    
            var tyleymaxParameter = tyleymax != null ?
                new ObjectParameter("tyleymax", tyleymax) :
                new ObjectParameter("tyleymax", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_PhuSon", tensanphamParameter, loaiphimParameter, tylexminParameter, tylexmaxParameter, tyleyminParameter, tyleymaxParameter);
        }
    
        public virtual int Insert_TaoMach(string tensanpham, string loaiphim, string tylex, string tyley)
        {
            var tensanphamParameter = tensanpham != null ?
                new ObjectParameter("tensanpham", tensanpham) :
                new ObjectParameter("tensanpham", typeof(string));
    
            var loaiphimParameter = loaiphim != null ?
                new ObjectParameter("loaiphim", loaiphim) :
                new ObjectParameter("loaiphim", typeof(string));
    
            var tylexParameter = tylex != null ?
                new ObjectParameter("tylex", tylex) :
                new ObjectParameter("tylex", typeof(string));
    
            var tyleyParameter = tyley != null ?
                new ObjectParameter("tyley", tyley) :
                new ObjectParameter("tyley", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_TaoMach", tensanphamParameter, loaiphimParameter, tylexParameter, tyleyParameter);
        }
    
        public virtual int Insert_Test(string ca, Nullable<System.DateTime> ngay, string gio, string bophan, string tensanpham, string dulieungay, string loaiphim, Nullable<int> sobo, string tylex, string tyley, string nguoiyeucau, string noidungyeucau, string xacnhancam, string hientrang, string giohoanthanh, string ngayxuatxuong, string ngaybaophe, string noidungbaophe)
        {
            var caParameter = ca != null ?
                new ObjectParameter("ca", ca) :
                new ObjectParameter("ca", typeof(string));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            var gioParameter = gio != null ?
                new ObjectParameter("gio", gio) :
                new ObjectParameter("gio", typeof(string));
    
            var bophanParameter = bophan != null ?
                new ObjectParameter("bophan", bophan) :
                new ObjectParameter("bophan", typeof(string));
    
            var tensanphamParameter = tensanpham != null ?
                new ObjectParameter("tensanpham", tensanpham) :
                new ObjectParameter("tensanpham", typeof(string));
    
            var dulieungayParameter = dulieungay != null ?
                new ObjectParameter("dulieungay", dulieungay) :
                new ObjectParameter("dulieungay", typeof(string));
    
            var loaiphimParameter = loaiphim != null ?
                new ObjectParameter("loaiphim", loaiphim) :
                new ObjectParameter("loaiphim", typeof(string));
    
            var soboParameter = sobo.HasValue ?
                new ObjectParameter("sobo", sobo) :
                new ObjectParameter("sobo", typeof(int));
    
            var tylexParameter = tylex != null ?
                new ObjectParameter("tylex", tylex) :
                new ObjectParameter("tylex", typeof(string));
    
            var tyleyParameter = tyley != null ?
                new ObjectParameter("tyley", tyley) :
                new ObjectParameter("tyley", typeof(string));
    
            var nguoiyeucauParameter = nguoiyeucau != null ?
                new ObjectParameter("nguoiyeucau", nguoiyeucau) :
                new ObjectParameter("nguoiyeucau", typeof(string));
    
            var noidungyeucauParameter = noidungyeucau != null ?
                new ObjectParameter("noidungyeucau", noidungyeucau) :
                new ObjectParameter("noidungyeucau", typeof(string));
    
            var xacnhancamParameter = xacnhancam != null ?
                new ObjectParameter("xacnhancam", xacnhancam) :
                new ObjectParameter("xacnhancam", typeof(string));
    
            var hientrangParameter = hientrang != null ?
                new ObjectParameter("hientrang", hientrang) :
                new ObjectParameter("hientrang", typeof(string));
    
            var giohoanthanhParameter = giohoanthanh != null ?
                new ObjectParameter("giohoanthanh", giohoanthanh) :
                new ObjectParameter("giohoanthanh", typeof(string));
    
            var ngayxuatxuongParameter = ngayxuatxuong != null ?
                new ObjectParameter("ngayxuatxuong", ngayxuatxuong) :
                new ObjectParameter("ngayxuatxuong", typeof(string));
    
            var ngaybaopheParameter = ngaybaophe != null ?
                new ObjectParameter("ngaybaophe", ngaybaophe) :
                new ObjectParameter("ngaybaophe", typeof(string));
    
            var noidungbaopheParameter = noidungbaophe != null ?
                new ObjectParameter("noidungbaophe", noidungbaophe) :
                new ObjectParameter("noidungbaophe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Test", caParameter, ngayParameter, gioParameter, bophanParameter, tensanphamParameter, dulieungayParameter, loaiphimParameter, soboParameter, tylexParameter, tyleyParameter, nguoiyeucauParameter, noidungyeucauParameter, xacnhancamParameter, hientrangParameter, giohoanthanhParameter, ngayxuatxuongParameter, ngaybaopheParameter, noidungbaopheParameter);
        }
    
        public virtual ObjectResult<KiemTraTyLePhuSon_Result> KiemTraTyLePhuSon(string tensanpham, string loaiphim)
        {
            var tensanphamParameter = tensanpham != null ?
                new ObjectParameter("tensanpham", tensanpham) :
                new ObjectParameter("tensanpham", typeof(string));
    
            var loaiphimParameter = loaiphim != null ?
                new ObjectParameter("loaiphim", loaiphim) :
                new ObjectParameter("loaiphim", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KiemTraTyLePhuSon_Result>("KiemTraTyLePhuSon", tensanphamParameter, loaiphimParameter);
        }
    
        public virtual ObjectResult<KiemTraTyLeTaoMach_Result> KiemTraTyLeTaoMach(string tensanpham, string loaiphim)
        {
            var tensanphamParameter = tensanpham != null ?
                new ObjectParameter("tensanpham", tensanpham) :
                new ObjectParameter("tensanpham", typeof(string));
    
            var loaiphimParameter = loaiphim != null ?
                new ObjectParameter("loaiphim", loaiphim) :
                new ObjectParameter("loaiphim", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KiemTraTyLeTaoMach_Result>("KiemTraTyLeTaoMach", tensanphamParameter, loaiphimParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> MaxSoBo_Fpc(string bophan, string tensanpham, string loaiphim)
        {
            var bophanParameter = bophan != null ?
                new ObjectParameter("bophan", bophan) :
                new ObjectParameter("bophan", typeof(string));
    
            var tensanphamParameter = tensanpham != null ?
                new ObjectParameter("tensanpham", tensanpham) :
                new ObjectParameter("tensanpham", typeof(string));
    
            var loaiphimParameter = loaiphim != null ?
                new ObjectParameter("loaiphim", loaiphim) :
                new ObjectParameter("loaiphim", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxSoBo_Fpc", bophanParameter, tensanphamParameter, loaiphimParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> MaxSoBo_PhimPcb(string masanpham, string loaiphim)
        {
            var masanphamParameter = masanpham != null ?
                new ObjectParameter("masanpham", masanpham) :
                new ObjectParameter("masanpham", typeof(string));
    
            var loaiphimParameter = loaiphim != null ?
                new ObjectParameter("loaiphim", loaiphim) :
                new ObjectParameter("loaiphim", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxSoBo_PhimPcb", masanphamParameter, loaiphimParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> MaxSoBo_Test(string bophan, string tensanpham, string loaiphim)
        {
            var bophanParameter = bophan != null ?
                new ObjectParameter("bophan", bophan) :
                new ObjectParameter("bophan", typeof(string));
    
            var tensanphamParameter = tensanpham != null ?
                new ObjectParameter("tensanpham", tensanpham) :
                new ObjectParameter("tensanpham", typeof(string));
    
            var loaiphimParameter = loaiphim != null ?
                new ObjectParameter("loaiphim", loaiphim) :
                new ObjectParameter("loaiphim", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxSoBo_Test", bophanParameter, tensanphamParameter, loaiphimParameter);
        }
    
        public virtual ObjectResult<SelectGiamDanFpc_Result> SelectGiamDanFpc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectGiamDanFpc_Result>("SelectGiamDanFpc");
        }
    
        public virtual ObjectResult<SelectGiamDanPhimPcb_Result> SelectGiamDanPhimPcb()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectGiamDanPhimPcb_Result>("SelectGiamDanPhimPcb");
        }
    
        public virtual ObjectResult<SelectGiamDanTest_Result> SelectGiamDanTest()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectGiamDanTest_Result>("SelectGiamDanTest");
        }
    
        public virtual ObjectResult<SelectIdFpc_Result> SelectIdFpc(Nullable<int> idfpc)
        {
            var idfpcParameter = idfpc.HasValue ?
                new ObjectParameter("idfpc", idfpc) :
                new ObjectParameter("idfpc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectIdFpc_Result>("SelectIdFpc", idfpcParameter);
        }
    
        public virtual ObjectResult<SelectIdLoaiPhim_Result> SelectIdLoaiPhim(Nullable<int> idloaiphim)
        {
            var idloaiphimParameter = idloaiphim.HasValue ?
                new ObjectParameter("idloaiphim", idloaiphim) :
                new ObjectParameter("idloaiphim", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectIdLoaiPhim_Result>("SelectIdLoaiPhim", idloaiphimParameter);
        }
    
        public virtual ObjectResult<SelectIdPcb_Result> SelectIdPcb(Nullable<int> idpcb)
        {
            var idpcbParameter = idpcb.HasValue ?
                new ObjectParameter("idpcb", idpcb) :
                new ObjectParameter("idpcb", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectIdPcb_Result>("SelectIdPcb", idpcbParameter);
        }
    
        public virtual ObjectResult<SelectIdPhuSon_Result> SelectIdPhuSon(Nullable<int> idphuson)
        {
            var idphusonParameter = idphuson.HasValue ?
                new ObjectParameter("idphuson", idphuson) :
                new ObjectParameter("idphuson", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectIdPhuSon_Result>("SelectIdPhuSon", idphusonParameter);
        }
    
        public virtual ObjectResult<SelectIdTaoMach_Result> SelectIdTaoMach(Nullable<int> idtaomach)
        {
            var idtaomachParameter = idtaomach.HasValue ?
                new ObjectParameter("idtaomach", idtaomach) :
                new ObjectParameter("idtaomach", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectIdTaoMach_Result>("SelectIdTaoMach", idtaomachParameter);
        }
    
        public virtual ObjectResult<SelectIdTest_Result> SelectIdTest(Nullable<int> idtest)
        {
            var idtestParameter = idtest.HasValue ?
                new ObjectParameter("idtest", idtest) :
                new ObjectParameter("idtest", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectIdTest_Result>("SelectIdTest", idtestParameter);
        }
    
        public virtual ObjectResult<string> SelectLoaiPhim()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SelectLoaiPhim");
        }
    
        public virtual ObjectResult<SelectNgayFpc_Result> SelectNgayFpc(Nullable<System.DateTime> ngaydau, Nullable<System.DateTime> ngaycuoi)
        {
            var ngaydauParameter = ngaydau.HasValue ?
                new ObjectParameter("ngaydau", ngaydau) :
                new ObjectParameter("ngaydau", typeof(System.DateTime));
    
            var ngaycuoiParameter = ngaycuoi.HasValue ?
                new ObjectParameter("ngaycuoi", ngaycuoi) :
                new ObjectParameter("ngaycuoi", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectNgayFpc_Result>("SelectNgayFpc", ngaydauParameter, ngaycuoiParameter);
        }
    
        public virtual ObjectResult<SelectNgayPcb_Result> SelectNgayPcb(Nullable<System.DateTime> ngaydau, Nullable<System.DateTime> ngaycuoi)
        {
            var ngaydauParameter = ngaydau.HasValue ?
                new ObjectParameter("ngaydau", ngaydau) :
                new ObjectParameter("ngaydau", typeof(System.DateTime));
    
            var ngaycuoiParameter = ngaycuoi.HasValue ?
                new ObjectParameter("ngaycuoi", ngaycuoi) :
                new ObjectParameter("ngaycuoi", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectNgayPcb_Result>("SelectNgayPcb", ngaydauParameter, ngaycuoiParameter);
        }
    
        public virtual ObjectResult<SelectNgayPhimTest_Result> SelectNgayPhimTest(Nullable<System.DateTime> ngaydau, Nullable<System.DateTime> ngaycuoi)
        {
            var ngaydauParameter = ngaydau.HasValue ?
                new ObjectParameter("ngaydau", ngaydau) :
                new ObjectParameter("ngaydau", typeof(System.DateTime));
    
            var ngaycuoiParameter = ngaycuoi.HasValue ?
                new ObjectParameter("ngaycuoi", ngaycuoi) :
                new ObjectParameter("ngaycuoi", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectNgayPhimTest_Result>("SelectNgayPhimTest", ngaydauParameter, ngaycuoiParameter);
        }
    
        public virtual ObjectResult<SelectPhusonLoaiPhim_Result> SelectPhusonLoaiPhim(string tensanpham, string loaiphim)
        {
            var tensanphamParameter = tensanpham != null ?
                new ObjectParameter("tensanpham", tensanpham) :
                new ObjectParameter("tensanpham", typeof(string));
    
            var loaiphimParameter = loaiphim != null ?
                new ObjectParameter("loaiphim", loaiphim) :
                new ObjectParameter("loaiphim", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectPhusonLoaiPhim_Result>("SelectPhusonLoaiPhim", tensanphamParameter, loaiphimParameter);
        }
    
        public virtual ObjectResult<SelectTaoMachLoaiPhim_Result> SelectTaoMachLoaiPhim(string tensanpham, string loaiphim)
        {
            var tensanphamParameter = tensanpham != null ?
                new ObjectParameter("tensanpham", tensanpham) :
                new ObjectParameter("tensanpham", typeof(string));
    
            var loaiphimParameter = loaiphim != null ?
                new ObjectParameter("loaiphim", loaiphim) :
                new ObjectParameter("loaiphim", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectTaoMachLoaiPhim_Result>("SelectTaoMachLoaiPhim", tensanphamParameter, loaiphimParameter);
        }
    
        public virtual ObjectResult<SelectTimKiemFpc_Result> SelectTimKiemFpc(string tensanpham, string loaiphim)
        {
            var tensanphamParameter = tensanpham != null ?
                new ObjectParameter("tensanpham", tensanpham) :
                new ObjectParameter("tensanpham", typeof(string));
    
            var loaiphimParameter = loaiphim != null ?
                new ObjectParameter("loaiphim", loaiphim) :
                new ObjectParameter("loaiphim", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectTimKiemFpc_Result>("SelectTimKiemFpc", tensanphamParameter, loaiphimParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<Test_Result> Test(string fromDate, string toDate)
        {
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Test_Result>("Test", fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<TimKiemSelectPhimPcb_Result> TimKiemSelectPhimPcb(string masanpham, string loaiphim)
        {
            var masanphamParameter = masanpham != null ?
                new ObjectParameter("masanpham", masanpham) :
                new ObjectParameter("masanpham", typeof(string));
    
            var loaiphimParameter = loaiphim != null ?
                new ObjectParameter("loaiphim", loaiphim) :
                new ObjectParameter("loaiphim", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimKiemSelectPhimPcb_Result>("TimKiemSelectPhimPcb", masanphamParameter, loaiphimParameter);
        }
    
        public virtual int UpDateFpc(Nullable<int> idfpc, string bophan, string tensanpham, string phanloai, string loaiphim, string tylex, string tyley, string nguoiyeucau, string noidungyeucau, string xacnhancam, string mayin, string hientrang, string giohoanthanh, string ngayxuatxuong, string ngaybaophe, string noidungbaophe)
        {
            var idfpcParameter = idfpc.HasValue ?
                new ObjectParameter("idfpc", idfpc) :
                new ObjectParameter("idfpc", typeof(int));
    
            var bophanParameter = bophan != null ?
                new ObjectParameter("bophan", bophan) :
                new ObjectParameter("bophan", typeof(string));
    
            var tensanphamParameter = tensanpham != null ?
                new ObjectParameter("tensanpham", tensanpham) :
                new ObjectParameter("tensanpham", typeof(string));
    
            var phanloaiParameter = phanloai != null ?
                new ObjectParameter("phanloai", phanloai) :
                new ObjectParameter("phanloai", typeof(string));
    
            var loaiphimParameter = loaiphim != null ?
                new ObjectParameter("loaiphim", loaiphim) :
                new ObjectParameter("loaiphim", typeof(string));
    
            var tylexParameter = tylex != null ?
                new ObjectParameter("tylex", tylex) :
                new ObjectParameter("tylex", typeof(string));
    
            var tyleyParameter = tyley != null ?
                new ObjectParameter("tyley", tyley) :
                new ObjectParameter("tyley", typeof(string));
    
            var nguoiyeucauParameter = nguoiyeucau != null ?
                new ObjectParameter("nguoiyeucau", nguoiyeucau) :
                new ObjectParameter("nguoiyeucau", typeof(string));
    
            var noidungyeucauParameter = noidungyeucau != null ?
                new ObjectParameter("noidungyeucau", noidungyeucau) :
                new ObjectParameter("noidungyeucau", typeof(string));
    
            var xacnhancamParameter = xacnhancam != null ?
                new ObjectParameter("xacnhancam", xacnhancam) :
                new ObjectParameter("xacnhancam", typeof(string));
    
            var mayinParameter = mayin != null ?
                new ObjectParameter("mayin", mayin) :
                new ObjectParameter("mayin", typeof(string));
    
            var hientrangParameter = hientrang != null ?
                new ObjectParameter("hientrang", hientrang) :
                new ObjectParameter("hientrang", typeof(string));
    
            var giohoanthanhParameter = giohoanthanh != null ?
                new ObjectParameter("giohoanthanh", giohoanthanh) :
                new ObjectParameter("giohoanthanh", typeof(string));
    
            var ngayxuatxuongParameter = ngayxuatxuong != null ?
                new ObjectParameter("ngayxuatxuong", ngayxuatxuong) :
                new ObjectParameter("ngayxuatxuong", typeof(string));
    
            var ngaybaopheParameter = ngaybaophe != null ?
                new ObjectParameter("ngaybaophe", ngaybaophe) :
                new ObjectParameter("ngaybaophe", typeof(string));
    
            var noidungbaopheParameter = noidungbaophe != null ?
                new ObjectParameter("noidungbaophe", noidungbaophe) :
                new ObjectParameter("noidungbaophe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpDateFpc", idfpcParameter, bophanParameter, tensanphamParameter, phanloaiParameter, loaiphimParameter, tylexParameter, tyleyParameter, nguoiyeucauParameter, noidungyeucauParameter, xacnhancamParameter, mayinParameter, hientrangParameter, giohoanthanhParameter, ngayxuatxuongParameter, ngaybaopheParameter, noidungbaopheParameter);
        }
    
        public virtual int UpDateLoaiPhim(Nullable<int> idloaiphim, string loaiphim)
        {
            var idloaiphimParameter = idloaiphim.HasValue ?
                new ObjectParameter("idloaiphim", idloaiphim) :
                new ObjectParameter("idloaiphim", typeof(int));
    
            var loaiphimParameter = loaiphim != null ?
                new ObjectParameter("loaiphim", loaiphim) :
                new ObjectParameter("loaiphim", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpDateLoaiPhim", idloaiphimParameter, loaiphimParameter);
        }
    
        public virtual int UpDatePcb(Nullable<int> idpcb, string bophan, string masanpham, string phanloai, string loaiphim, string maydung, string tylex, string tyley, string nguoiyeucau, string noidungyeucau, string xacnhancam, string mayin, string hientrang, string giohoanthanh, string ngayxuatxuong, string ngaybaophe, string noidungbaophe)
        {
            var idpcbParameter = idpcb.HasValue ?
                new ObjectParameter("idpcb", idpcb) :
                new ObjectParameter("idpcb", typeof(int));
    
            var bophanParameter = bophan != null ?
                new ObjectParameter("bophan", bophan) :
                new ObjectParameter("bophan", typeof(string));
    
            var masanphamParameter = masanpham != null ?
                new ObjectParameter("masanpham", masanpham) :
                new ObjectParameter("masanpham", typeof(string));
    
            var phanloaiParameter = phanloai != null ?
                new ObjectParameter("phanloai", phanloai) :
                new ObjectParameter("phanloai", typeof(string));
    
            var loaiphimParameter = loaiphim != null ?
                new ObjectParameter("loaiphim", loaiphim) :
                new ObjectParameter("loaiphim", typeof(string));
    
            var maydungParameter = maydung != null ?
                new ObjectParameter("maydung", maydung) :
                new ObjectParameter("maydung", typeof(string));
    
            var tylexParameter = tylex != null ?
                new ObjectParameter("tylex", tylex) :
                new ObjectParameter("tylex", typeof(string));
    
            var tyleyParameter = tyley != null ?
                new ObjectParameter("tyley", tyley) :
                new ObjectParameter("tyley", typeof(string));
    
            var nguoiyeucauParameter = nguoiyeucau != null ?
                new ObjectParameter("nguoiyeucau", nguoiyeucau) :
                new ObjectParameter("nguoiyeucau", typeof(string));
    
            var noidungyeucauParameter = noidungyeucau != null ?
                new ObjectParameter("noidungyeucau", noidungyeucau) :
                new ObjectParameter("noidungyeucau", typeof(string));
    
            var xacnhancamParameter = xacnhancam != null ?
                new ObjectParameter("xacnhancam", xacnhancam) :
                new ObjectParameter("xacnhancam", typeof(string));
    
            var mayinParameter = mayin != null ?
                new ObjectParameter("mayin", mayin) :
                new ObjectParameter("mayin", typeof(string));
    
            var hientrangParameter = hientrang != null ?
                new ObjectParameter("hientrang", hientrang) :
                new ObjectParameter("hientrang", typeof(string));
    
            var giohoanthanhParameter = giohoanthanh != null ?
                new ObjectParameter("giohoanthanh", giohoanthanh) :
                new ObjectParameter("giohoanthanh", typeof(string));
    
            var ngayxuatxuongParameter = ngayxuatxuong != null ?
                new ObjectParameter("ngayxuatxuong", ngayxuatxuong) :
                new ObjectParameter("ngayxuatxuong", typeof(string));
    
            var ngaybaopheParameter = ngaybaophe != null ?
                new ObjectParameter("ngaybaophe", ngaybaophe) :
                new ObjectParameter("ngaybaophe", typeof(string));
    
            var noidungbaopheParameter = noidungbaophe != null ?
                new ObjectParameter("noidungbaophe", noidungbaophe) :
                new ObjectParameter("noidungbaophe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpDatePcb", idpcbParameter, bophanParameter, masanphamParameter, phanloaiParameter, loaiphimParameter, maydungParameter, tylexParameter, tyleyParameter, nguoiyeucauParameter, noidungyeucauParameter, xacnhancamParameter, mayinParameter, hientrangParameter, giohoanthanhParameter, ngayxuatxuongParameter, ngaybaopheParameter, noidungbaopheParameter);
        }
    
        public virtual int UpDatePhuSon(Nullable<int> idphuson, string tensanpham, string loaiphim, string tylexmin, string tylexmax, string tyleymin, string tyleymax)
        {
            var idphusonParameter = idphuson.HasValue ?
                new ObjectParameter("idphuson", idphuson) :
                new ObjectParameter("idphuson", typeof(int));
    
            var tensanphamParameter = tensanpham != null ?
                new ObjectParameter("tensanpham", tensanpham) :
                new ObjectParameter("tensanpham", typeof(string));
    
            var loaiphimParameter = loaiphim != null ?
                new ObjectParameter("loaiphim", loaiphim) :
                new ObjectParameter("loaiphim", typeof(string));
    
            var tylexminParameter = tylexmin != null ?
                new ObjectParameter("tylexmin", tylexmin) :
                new ObjectParameter("tylexmin", typeof(string));
    
            var tylexmaxParameter = tylexmax != null ?
                new ObjectParameter("tylexmax", tylexmax) :
                new ObjectParameter("tylexmax", typeof(string));
    
            var tyleyminParameter = tyleymin != null ?
                new ObjectParameter("tyleymin", tyleymin) :
                new ObjectParameter("tyleymin", typeof(string));
    
            var tyleymaxParameter = tyleymax != null ?
                new ObjectParameter("tyleymax", tyleymax) :
                new ObjectParameter("tyleymax", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpDatePhuSon", idphusonParameter, tensanphamParameter, loaiphimParameter, tylexminParameter, tylexmaxParameter, tyleyminParameter, tyleymaxParameter);
        }
    
        public virtual int UpDateTaoMach(Nullable<int> idtaomach, string tensanpham, string loaiphim, string tylex, string tyley)
        {
            var idtaomachParameter = idtaomach.HasValue ?
                new ObjectParameter("idtaomach", idtaomach) :
                new ObjectParameter("idtaomach", typeof(int));
    
            var tensanphamParameter = tensanpham != null ?
                new ObjectParameter("tensanpham", tensanpham) :
                new ObjectParameter("tensanpham", typeof(string));
    
            var loaiphimParameter = loaiphim != null ?
                new ObjectParameter("loaiphim", loaiphim) :
                new ObjectParameter("loaiphim", typeof(string));
    
            var tylexParameter = tylex != null ?
                new ObjectParameter("tylex", tylex) :
                new ObjectParameter("tylex", typeof(string));
    
            var tyleyParameter = tyley != null ?
                new ObjectParameter("tyley", tyley) :
                new ObjectParameter("tyley", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpDateTaoMach", idtaomachParameter, tensanphamParameter, loaiphimParameter, tylexParameter, tyleyParameter);
        }
    
        public virtual int UpDateTest(Nullable<int> idtest, string tylex, string tyley, string dulieungay, string xacnhancam, string hientrang, string giohoanthanh, string ngayxuatxuong, string ngaybaophe, string noidungbaophe)
        {
            var idtestParameter = idtest.HasValue ?
                new ObjectParameter("idtest", idtest) :
                new ObjectParameter("idtest", typeof(int));
    
            var tylexParameter = tylex != null ?
                new ObjectParameter("tylex", tylex) :
                new ObjectParameter("tylex", typeof(string));
    
            var tyleyParameter = tyley != null ?
                new ObjectParameter("tyley", tyley) :
                new ObjectParameter("tyley", typeof(string));
    
            var dulieungayParameter = dulieungay != null ?
                new ObjectParameter("dulieungay", dulieungay) :
                new ObjectParameter("dulieungay", typeof(string));
    
            var xacnhancamParameter = xacnhancam != null ?
                new ObjectParameter("xacnhancam", xacnhancam) :
                new ObjectParameter("xacnhancam", typeof(string));
    
            var hientrangParameter = hientrang != null ?
                new ObjectParameter("hientrang", hientrang) :
                new ObjectParameter("hientrang", typeof(string));
    
            var giohoanthanhParameter = giohoanthanh != null ?
                new ObjectParameter("giohoanthanh", giohoanthanh) :
                new ObjectParameter("giohoanthanh", typeof(string));
    
            var ngayxuatxuongParameter = ngayxuatxuong != null ?
                new ObjectParameter("ngayxuatxuong", ngayxuatxuong) :
                new ObjectParameter("ngayxuatxuong", typeof(string));
    
            var ngaybaopheParameter = ngaybaophe != null ?
                new ObjectParameter("ngaybaophe", ngaybaophe) :
                new ObjectParameter("ngaybaophe", typeof(string));
    
            var noidungbaopheParameter = noidungbaophe != null ?
                new ObjectParameter("noidungbaophe", noidungbaophe) :
                new ObjectParameter("noidungbaophe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpDateTest", idtestParameter, tylexParameter, tyleyParameter, dulieungayParameter, xacnhancamParameter, hientrangParameter, giohoanthanhParameter, ngayxuatxuongParameter, ngaybaopheParameter, noidungbaopheParameter);
        }
    
        public virtual int UpDateXacNhan(Nullable<int> idpcb, string bophan, string masanpham, string phanloai, string loaiphim, string maydung, string tylex, string tyley, string nguoiyeucau, string noidungyeucau, string xacnhanpe, string hientrang)
        {
            var idpcbParameter = idpcb.HasValue ?
                new ObjectParameter("idpcb", idpcb) :
                new ObjectParameter("idpcb", typeof(int));
    
            var bophanParameter = bophan != null ?
                new ObjectParameter("bophan", bophan) :
                new ObjectParameter("bophan", typeof(string));
    
            var masanphamParameter = masanpham != null ?
                new ObjectParameter("masanpham", masanpham) :
                new ObjectParameter("masanpham", typeof(string));
    
            var phanloaiParameter = phanloai != null ?
                new ObjectParameter("phanloai", phanloai) :
                new ObjectParameter("phanloai", typeof(string));
    
            var loaiphimParameter = loaiphim != null ?
                new ObjectParameter("loaiphim", loaiphim) :
                new ObjectParameter("loaiphim", typeof(string));
    
            var maydungParameter = maydung != null ?
                new ObjectParameter("maydung", maydung) :
                new ObjectParameter("maydung", typeof(string));
    
            var tylexParameter = tylex != null ?
                new ObjectParameter("tylex", tylex) :
                new ObjectParameter("tylex", typeof(string));
    
            var tyleyParameter = tyley != null ?
                new ObjectParameter("tyley", tyley) :
                new ObjectParameter("tyley", typeof(string));
    
            var nguoiyeucauParameter = nguoiyeucau != null ?
                new ObjectParameter("nguoiyeucau", nguoiyeucau) :
                new ObjectParameter("nguoiyeucau", typeof(string));
    
            var noidungyeucauParameter = noidungyeucau != null ?
                new ObjectParameter("noidungyeucau", noidungyeucau) :
                new ObjectParameter("noidungyeucau", typeof(string));
    
            var xacnhanpeParameter = xacnhanpe != null ?
                new ObjectParameter("xacnhanpe", xacnhanpe) :
                new ObjectParameter("xacnhanpe", typeof(string));
    
            var hientrangParameter = hientrang != null ?
                new ObjectParameter("hientrang", hientrang) :
                new ObjectParameter("hientrang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpDateXacNhan", idpcbParameter, bophanParameter, masanphamParameter, phanloaiParameter, loaiphimParameter, maydungParameter, tylexParameter, tyleyParameter, nguoiyeucauParameter, noidungyeucauParameter, xacnhanpeParameter, hientrangParameter);
        }
    
        public virtual ObjectResult<CoDinhTyLePhuSon> SelectPhuSon()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CoDinhTyLePhuSon>("SelectPhuSon");
        }
    
        public virtual ObjectResult<CoDinhTyLePhuSon> SelectPhuSon(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CoDinhTyLePhuSon>("SelectPhuSon", mergeOption);
        }
    }
}
